import type {
  ManagedConfigRecord,
  ManagedDeptRecord,
  ManagedDictDataRecord,
  ManagedDictTypeRecord,
  ManagedMenuRecord,
  ManagedNoticeRecord,
  ManagedPostRecord,
  ManagedRoleRecord,
  ManagedUserRecord,
} from "../src/modules/rbac/domain/rbac.types";
import { hashText } from "../src/shared/common/security/hash.util";

export type SystemManagementState = {
  depts: ManagedDeptRecord[];
  posts: ManagedPostRecord[];
  menus: ManagedMenuRecord[];
  roles: ManagedRoleRecord[];
  dictTypes: ManagedDictTypeRecord[];
  dictData: ManagedDictDataRecord[];
  configs: ManagedConfigRecord[];
  notices: ManagedNoticeRecord[];
  users: ManagedUserRecord[];
};

const ALL_PERMISSION = "*:*:*";

const WAREHOUSE_MANAGER_PERMISSION_PRESET = [
  "dashboard:view",
  "master:material-category:list",
  "master:material-category:create",
  "master:material-category:update",
  "master:material-category:deactivate",
  "master:material:list",
  "master:material:create",
  "master:material:update",
  "master:material:deactivate",
  "master:customer:list",
  "master:customer:create",
  "master:customer:update",
  "master:customer:deactivate",
  "master:supplier:list",
  "master:supplier:create",
  "master:supplier:update",
  "master:supplier:deactivate",
  "master:personnel:list",
  "master:personnel:create",
  "master:personnel:update",
  "master:personnel:deactivate",
  "master:workshop:list",
  "master:workshop:create",
  "master:workshop:update",
  "master:workshop:deactivate",
  "master:stock-scope:list",
  "master:stock-scope:create",
  "master:stock-scope:update",
  "master:stock-scope:deactivate",
  "inbound:order:list",
  "inbound:order:create",
  "inbound:order:update",
  "inbound:order:void",
  "inbound:into-order:list",
  "inbound:into-order:create",
  "inbound:into-order:update",
  "inbound:into-order:void",
  "workshop-material:pick-order:list",
  "workshop-material:pick-order:create",
  "workshop-material:pick-order:update",
  "workshop-material:pick-order:void",
  "workshop-material:return-order:list",
  "workshop-material:return-order:create",
  "workshop-material:return-order:update",
  "workshop-material:return-order:void",
  "workshop-material:scrap-order:list",
  "workshop-material:scrap-order:create",
  "workshop-material:scrap-order:update",
  "workshop-material:scrap-order:void",
  "inventory:balance:list",
  "inventory:factory-number:list",
  "inventory:log:list",
  "inventory:source-usage:list",
  "sales:order:list",
  "sales:order:create",
  "sales:order:update",
  "sales:order:void",
  "sales:return:list",
  "sales:return:create",
  "sales:return:void",
  "sales:project:list",
  "sales:project:get",
  "sales:project:create",
  "sales:project:update",
  "sales:project:void",
  "sales:project:draft",
  "rd:procurement-request:list",
  "rd:procurement-request:return-action",
  "rd:handoff-order:list",
];

const RD_OPERATOR_PERMISSION_PRESET = [
  "dashboard:view",
  "rd:procurement-request:list",
  "rd:procurement-request:create",
  "rd:procurement-request:void",
  "rd:procurement-request:status-action",
  "rd:workbench:view",
  "reporting:home:view",
  "reporting:inventory-summary:view",
  "reporting:material-category-summary:view",
  "reporting:monthly-reporting:view",
  "inventory:balance:list",
  "inventory:log:list",
  "rd:handoff-order:list",
  "rd:stocktake-order:list",
  "rd:stocktake-order:create",
  "rd:stocktake-order:void",
  "rd:project:list",
  "rd:project:get",
  "rd:project:create",
  "rd:project:void",
  "workshop-material:scrap-order:list",
  "workshop-material:scrap-order:create",
  "workshop-material:scrap-order:update",
  "workshop-material:scrap-order:void",
  "master:material:list",
];

const PROCUREMENT_PERMISSION_PRESET = [
  "dashboard:view",
  "ai:chat",
  "ai:tools:list",
  "rd:procurement-request:list",
  "rd:procurement-request:status-action",
  "master:supplier:list",
  "inbound:order:list",
];

// 这些只用于首次初始化默认角色授权；运行态权限真源仍由角色菜单关系承接。
const DEFAULT_ROLE_PERMISSION_ASSIGNMENTS: Record<string, string[]> = {
  "warehouse-manager": WAREHOUSE_MANAGER_PERMISSION_PRESET,
  "rd-operator": RD_OPERATOR_PERMISSION_PRESET,
  procurement: PROCUREMENT_PERMISSION_PRESET,
};

export function createSystemManagementSeedState(): SystemManagementState {
  const depts: ManagedDeptRecord[] = [
    {
      deptId: 100,
      parentId: 0,
      ancestors: "0",
      deptName: "研发部",
      orderNum: 1,
      leader: "研发负责人",
      phone: "13800000001",
      email: "rd@saifute.local",
      status: "0",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      deptId: 200,
      parentId: 0,
      ancestors: "0",
      deptName: "采购部",
      orderNum: 2,
      leader: "采购负责人",
      phone: "13800000002",
      email: "procurement@saifute.local",
      status: "0",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      deptId: 300,
      parentId: 0,
      ancestors: "0",
      deptName: "仓库",
      orderNum: 3,
      leader: "仓库负责人",
      phone: "13800000003",
      email: "warehouse@saifute.local",
      status: "0",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
  ];

  const posts: ManagedPostRecord[] = [
    {
      postId: 1,
      postCode: "SYS_ADMIN",
      postName: "系统管理员",
      postSort: 1,
      status: "0",
      remark: "超级管理员岗位",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      postId: 2,
      postCode: "WAREHOUSE_MANAGER",
      postName: "仓库管理员",
      postSort: 2,
      status: "0",
      remark: "主仓与公司级实物流转岗位",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      postId: 3,
      postCode: "PROCUREMENT_STAFF",
      postName: "采购人员",
      postSort: 3,
      status: "0",
      remark: "采购执行岗位",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      postId: 4,
      postCode: "RD_SUBWAREHOUSE",
      postName: "研发小仓管理员",
      postSort: 4,
      status: "0",
      remark: "研发小仓专属岗位",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
  ];

  const menus: ManagedMenuRecord[] = [
    {
      menuId: 1900,
      parentId: 0,
      menuName: "首页",
      orderNum: 0,
      path: "/dashboard",
      component: "dashboard/index",
      routeName: "Dashboard",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "dashboard:view",
      icon: "dashboard",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2000,
      parentId: 0,
      menuName: "系统管理",
      orderNum: 1,
      path: "/system",
      component: "Layout",
      routeName: "SystemManagement",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "system",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2100,
      parentId: 2000,
      menuName: "用户管理",
      orderNum: 1,
      path: "user",
      component: "system/user/index",
      routeName: "SystemUser",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "system:user:list",
      icon: "user",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2110,
      parentId: 2100,
      menuName: "用户新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:user:add",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2120,
      parentId: 2100,
      menuName: "用户修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:user:edit",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2130,
      parentId: 2100,
      menuName: "用户删除",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:user:remove",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2140,
      parentId: 2100,
      menuName: "重置密码",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:user:resetPwd",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2200,
      parentId: 2000,
      menuName: "角色管理",
      orderNum: 2,
      path: "role",
      component: "system/role/index",
      routeName: "SystemRole",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "system:role:list",
      icon: "peoples",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2210,
      parentId: 2200,
      menuName: "角色新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:role:add",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2220,
      parentId: 2200,
      menuName: "角色修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:role:edit",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2230,
      parentId: 2200,
      menuName: "角色删除",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:role:remove",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2300,
      parentId: 2000,
      menuName: "部门管理",
      orderNum: 3,
      path: "dept",
      component: "system/dept/index",
      routeName: "SystemDept",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "system:dept:list",
      icon: "tree",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2310,
      parentId: 2300,
      menuName: "部门新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:dept:add",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2320,
      parentId: 2300,
      menuName: "部门修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:dept:edit",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2330,
      parentId: 2300,
      menuName: "部门删除",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:dept:remove",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2400,
      parentId: 2000,
      menuName: "菜单管理",
      orderNum: 4,
      path: "menu",
      component: "system/menu/index",
      routeName: "SystemMenu",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "system:menu:list",
      icon: "tree-table",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2410,
      parentId: 2400,
      menuName: "菜单新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:menu:add",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2420,
      parentId: 2400,
      menuName: "菜单修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:menu:edit",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2430,
      parentId: 2400,
      menuName: "菜单删除",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:menu:remove",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2500,
      parentId: 2000,
      menuName: "岗位管理",
      orderNum: 5,
      path: "post",
      component: "system/post/index",
      routeName: "SystemPost",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "system:post:list",
      icon: "post",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2510,
      parentId: 2500,
      menuName: "岗位新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:post:add",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2520,
      parentId: 2500,
      menuName: "岗位修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:post:edit",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2530,
      parentId: 2500,
      menuName: "岗位删除",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:post:remove",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2600,
      parentId: 2000,
      menuName: "字典管理",
      orderNum: 6,
      path: "dict",
      component: "system/dict/index",
      routeName: "SystemDict",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "system:dict:list",
      icon: "dict",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2610,
      parentId: 2600,
      menuName: "字典新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:dict:add",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2620,
      parentId: 2600,
      menuName: "字典修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:dict:edit",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2630,
      parentId: 2600,
      menuName: "字典删除",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:dict:remove",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2700,
      parentId: 2000,
      menuName: "参数配置",
      orderNum: 7,
      path: "config",
      component: "system/config/index",
      routeName: "SystemConfig",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "system:config:list",
      icon: "edit",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2710,
      parentId: 2700,
      menuName: "参数新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:config:add",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2720,
      parentId: 2700,
      menuName: "参数修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:config:edit",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2730,
      parentId: 2700,
      menuName: "参数删除",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:config:remove",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2800,
      parentId: 2000,
      menuName: "通知公告",
      orderNum: 8,
      path: "notice",
      component: "system/notice/index",
      routeName: "SystemNotice",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "system:notice:list",
      icon: "message",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2810,
      parentId: 2800,
      menuName: "公告新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:notice:add",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2820,
      parentId: 2800,
      menuName: "公告修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:notice:edit",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2830,
      parentId: 2800,
      menuName: "公告删除",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:notice:remove",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2145,
      parentId: 2100,
      menuName: "用户导出",
      orderNum: 5,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:user:export",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2235,
      parentId: 2200,
      menuName: "角色导出",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:role:export",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2535,
      parentId: 2500,
      menuName: "岗位导出",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:post:export",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2635,
      parentId: 2600,
      menuName: "字典导出",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:dict:export",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2735,
      parentId: 2700,
      menuName: "参数导出",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "system:config:export",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2900,
      parentId: 0,
      menuName: "平台能力",
      orderNum: 9,
      path: "/platform",
      component: "Layout",
      routeName: "PlatformCapabilities",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "monitor",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2910,
      parentId: 2900,
      menuName: "首页报表",
      orderNum: 1,
      path: "reporting/home",
      component: "reporting/home/index",
      routeName: "ReportingHome",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "reporting:home:view",
      icon: "dashboard",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2911,
      parentId: 2900,
      menuName: "库存汇总报表",
      orderNum: 2,
      path: "reporting/inventory-summary",
      component: "reporting/inventory-summary/index",
      routeName: "InventorySummary",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "reporting:inventory-summary:view",
      icon: "chart",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2912,
      parentId: 2900,
      menuName: "物料类别汇总",
      orderNum: 3,
      path: "reporting/material-category-summary",
      component: "reporting/material-category-summary/index",
      routeName: "MaterialCategorySummary",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "reporting:material-category-summary:view",
      icon: "chart",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2913,
      parentId: 2900,
      menuName: "趋势报表",
      orderNum: 4,
      path: "reporting/trends",
      component: "reporting/trends/index",
      routeName: "ReportingTrends",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "reporting:trends:view",
      icon: "chart",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2914,
      parentId: 2900,
      menuName: "月度对账",
      orderNum: 5,
      path: "reporting/monthly-reporting",
      component: "reporting/monthly-reporting/index",
      routeName: "MonthlyReporting",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "reporting:monthly-reporting:view",
      icon: "table",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2915,
      parentId: 2900,
      menuName: "报表导出",
      orderNum: 6,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "reporting:export",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2920,
      parentId: 2900,
      menuName: "在线用户",
      orderNum: 6,
      path: "online",
      component: "monitor/online/index",
      routeName: "OnlineUsers",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "monitor:online:list",
      icon: "user",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2921,
      parentId: 2920,
      menuName: "强退在线用户",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "monitor:online:forceLogout",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2930,
      parentId: 2900,
      menuName: "登录日志",
      orderNum: 7,
      path: "logininfor",
      component: "monitor/logininfor/index",
      routeName: "LoginLogs",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "audit:login-log:list",
      icon: "form",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2931,
      parentId: 2930,
      menuName: "删除登录日志",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "audit:login-log:delete",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2940,
      parentId: 2900,
      menuName: "操作日志",
      orderNum: 8,
      path: "operlog",
      component: "monitor/operlog/index",
      routeName: "OperLogs",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "audit:oper-log:list",
      icon: "form",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 2941,
      parentId: 2940,
      menuName: "删除操作日志",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "audit:oper-log:delete",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3000,
      parentId: 0,
      menuName: "基础资料权限",
      orderNum: 10,
      path: "/base-auth",
      component: "Layout",
      routeName: "MasterDataPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "tree-table",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3010,
      parentId: 3000,
      menuName: "物料资料",
      orderNum: 1,
      path: "material",
      component: "base/material/index",
      routeName: "BaseMaterial",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "master:material:list",
      icon: "list",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3011,
      parentId: 3010,
      menuName: "物料新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:material:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3012,
      parentId: 3010,
      menuName: "物料修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:material:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3020,
      parentId: 3000,
      menuName: "客户资料",
      orderNum: 2,
      path: "customer",
      component: "base/customer/index",
      routeName: "BaseCustomer",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "master:customer:list",
      icon: "peoples",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3030,
      parentId: 3000,
      menuName: "供应商资料",
      orderNum: 3,
      path: "supplier",
      component: "base/supplier/index",
      routeName: "BaseSupplier",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "master:supplier:list",
      icon: "peoples",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3031,
      parentId: 3030,
      menuName: "供应商新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:supplier:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3032,
      parentId: 3030,
      menuName: "供应商修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:supplier:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3033,
      parentId: 3030,
      menuName: "供应商停用",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:supplier:deactivate",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3040,
      parentId: 3000,
      menuName: "人员资料",
      orderNum: 4,
      path: "personnel",
      component: "base/personnel/index",
      routeName: "BasePersonnel",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "master:personnel:list",
      icon: "user",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3050,
      parentId: 3000,
      menuName: "车间资料",
      orderNum: 5,
      path: "workshop",
      component: "base/workshop/index",
      routeName: "BaseWorkshop",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "master:workshop:list",
      icon: "tree",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3051,
      parentId: 3050,
      menuName: "车间新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:workshop:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3052,
      parentId: 3050,
      menuName: "车间修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:workshop:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3053,
      parentId: 3050,
      menuName: "车间停用",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:workshop:deactivate",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3060,
      parentId: 3000,
      menuName: "物料分类",
      orderNum: 6,
      path: "material-category",
      component: "base/material-category/index",
      routeName: "BaseMaterialCategory",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "master:material-category:list",
      icon: "cascader",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3061,
      parentId: 3060,
      menuName: "物料分类新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:material-category:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3062,
      parentId: 3060,
      menuName: "物料分类修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:material-category:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3063,
      parentId: 3060,
      menuName: "物料分类停用",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:material-category:deactivate",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3070,
      parentId: 3000,
      menuName: "库存范围",
      orderNum: 7,
      path: "stock-scope",
      component: "base/stock-scope/index",
      routeName: "BaseStockScope",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "master:stock-scope:list",
      icon: "nested",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3071,
      parentId: 3070,
      menuName: "库存范围新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:stock-scope:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3072,
      parentId: 3070,
      menuName: "库存范围修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:stock-scope:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3073,
      parentId: 3070,
      menuName: "库存范围停用",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:stock-scope:deactivate",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3013,
      parentId: 3010,
      menuName: "物料停用",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:material:deactivate",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3021,
      parentId: 3020,
      menuName: "客户新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:customer:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3022,
      parentId: 3020,
      menuName: "客户修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:customer:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3023,
      parentId: 3020,
      menuName: "客户停用",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:customer:deactivate",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3041,
      parentId: 3040,
      menuName: "人员新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:personnel:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3042,
      parentId: 3040,
      menuName: "人员修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:personnel:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3043,
      parentId: 3040,
      menuName: "人员停用",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "master:personnel:deactivate",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3100,
      parentId: 0,
      menuName: "入库业务权限",
      orderNum: 11,
      path: "/entry-auth",
      component: "Layout",
      routeName: "InboundPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "edit",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3110,
      parentId: 3100,
      menuName: "普通入库",
      orderNum: 1,
      path: "order",
      component: "entry/order/index",
      routeName: "EntryOrder",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "inbound:order:list",
      icon: "edit",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3111,
      parentId: 3110,
      menuName: "普通入库新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "inbound:order:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3112,
      parentId: 3110,
      menuName: "普通入库修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "inbound:order:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3113,
      parentId: 3110,
      menuName: "普通入库作废",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "inbound:order:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3120,
      parentId: 3100,
      menuName: "生产入库",
      orderNum: 2,
      path: "intoOrder",
      component: "entry/intoOrder/index",
      routeName: "EntryIntoOrder",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "inbound:into-order:list",
      icon: "edit",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3121,
      parentId: 3120,
      menuName: "生产入库新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "inbound:into-order:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3122,
      parentId: 3120,
      menuName: "生产入库修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "inbound:into-order:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3123,
      parentId: 3120,
      menuName: "生产入库作废",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "inbound:into-order:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3200,
      parentId: 0,
      menuName: "车间物料权限",
      orderNum: 12,
      path: "/take-auth",
      component: "Layout",
      routeName: "WorkshopMaterialPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "list",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3210,
      parentId: 3200,
      menuName: "领料单",
      orderNum: 1,
      path: "pickOrder",
      component: "take/pickOrder/index",
      routeName: "TakePickOrder",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "workshop-material:pick-order:list",
      icon: "list",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3211,
      parentId: 3210,
      menuName: "领料单新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "workshop-material:pick-order:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3212,
      parentId: 3210,
      menuName: "领料单作废",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "workshop-material:pick-order:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3213,
      parentId: 3210,
      menuName: "领料单修改",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "workshop-material:pick-order:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3220,
      parentId: 3200,
      menuName: "退料单",
      orderNum: 2,
      path: "returnOrder",
      component: "take/returnOrder/index",
      routeName: "TakeReturnOrder",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "workshop-material:return-order:list",
      icon: "list",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3221,
      parentId: 3220,
      menuName: "退料单新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "workshop-material:return-order:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3222,
      parentId: 3220,
      menuName: "退料单作废",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "workshop-material:return-order:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3223,
      parentId: 3220,
      menuName: "退料单修改",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "workshop-material:return-order:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3230,
      parentId: 3200,
      menuName: "报废单",
      orderNum: 3,
      path: "scrapOrder",
      component: "stock/scrapOrder/index",
      routeName: "StockScrapOrder",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "workshop-material:scrap-order:list",
      icon: "list",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3231,
      parentId: 3230,
      menuName: "报废单新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "workshop-material:scrap-order:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3232,
      parentId: 3230,
      menuName: "报废单作废",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "workshop-material:scrap-order:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3233,
      parentId: 3230,
      menuName: "报废单修改",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "workshop-material:scrap-order:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3300,
      parentId: 0,
      menuName: "库存管理权限",
      orderNum: 13,
      path: "/stock-auth",
      component: "Layout",
      routeName: "InventoryPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "chart",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3310,
      parentId: 3300,
      menuName: "库存余额",
      orderNum: 1,
      path: "inventory",
      component: "stock/inventory/index",
      routeName: "StockInventory",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "inventory:balance:list",
      icon: "chart",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3320,
      parentId: 3300,
      menuName: "库存流水",
      orderNum: 2,
      path: "log",
      component: "stock/log/index",
      routeName: "StockLog",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "inventory:log:list",
      icon: "chart",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3330,
      parentId: 3300,
      menuName: "来源追踪",
      orderNum: 3,
      path: "used",
      component: "stock/used/index",
      routeName: "StockUsed",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "inventory:source-usage:list",
      icon: "chart",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3340,
      parentId: 3300,
      menuName: "厂编区间",
      orderNum: 4,
      path: "interval",
      component: "stock/interval/index",
      routeName: "StockInterval",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "inventory:factory-number:list",
      icon: "chart",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3400,
      parentId: 0,
      menuName: "销售管理权限",
      orderNum: 14,
      path: "/sales-auth",
      component: "Layout",
      routeName: "SalesPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "peoples",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3410,
      parentId: 3400,
      menuName: "销售出库",
      orderNum: 1,
      path: "order",
      component: "sales/order/index",
      routeName: "SalesOrder",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "sales:order:list",
      icon: "peoples",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3411,
      parentId: 3410,
      menuName: "销售出库新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:order:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3412,
      parentId: 3410,
      menuName: "销售出库修改",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:order:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3413,
      parentId: 3410,
      menuName: "销售出库作废",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:order:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3420,
      parentId: 3400,
      menuName: "销售退货",
      orderNum: 2,
      path: "salesReturnOrder",
      component: "sales/salesReturnOrder/index",
      routeName: "SalesReturnOrder",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "sales:return:list",
      icon: "peoples",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3421,
      parentId: 3420,
      menuName: "销售退货新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:return:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3422,
      parentId: 3420,
      menuName: "销售退货作废",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:return:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3430,
      parentId: 3400,
      menuName: "销售项目",
      orderNum: 3,
      path: "project",
      component: "sales-project/index",
      routeName: "SalesProjectLedger",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "sales:project:list",
      icon: "peoples",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3431,
      parentId: 3430,
      menuName: "销售项目详情",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:project:get",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3432,
      parentId: 3430,
      menuName: "销售项目新增",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:project:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3433,
      parentId: 3430,
      menuName: "销售项目修改",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:project:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3434,
      parentId: 3430,
      menuName: "销售项目作废",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:project:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3435,
      parentId: 3430,
      menuName: "销售项目出库草稿",
      orderNum: 5,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "sales:project:draft",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3500,
      parentId: 0,
      menuName: "研发协同权限",
      orderNum: 15,
      path: "/rd-auth",
      component: "Layout",
      routeName: "RdPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "list",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3510,
      parentId: 3500,
      menuName: "RD 工作台",
      orderNum: 1,
      path: "workbench",
      component: "rd/workbench/index",
      routeName: "RdWorkbench",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "rd:workbench:view",
      icon: "dashboard",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3520,
      parentId: 3500,
      menuName: "RD 采购需求",
      orderNum: 2,
      path: "procurement-requests",
      component: "rd/procurement-requests/index",
      routeName: "RdProcurementRequests",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "rd:procurement-request:list",
      icon: "edit",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3521,
      parentId: 3520,
      menuName: "RD 采购需求新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:procurement-request:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3522,
      parentId: 3520,
      menuName: "RD 采购需求作废",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:procurement-request:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3523,
      parentId: 3520,
      menuName: "RD 采购状态动作",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:procurement-request:status-action",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3524,
      parentId: 3520,
      menuName: "RD 采购退回动作",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:procurement-request:return-action",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3530,
      parentId: 3500,
      menuName: "RD 交接结果",
      orderNum: 3,
      path: "handoff-results",
      component: "rd/inbound-results/index",
      routeName: "RdInboundResults",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "rd:handoff-order:list",
      icon: "list",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3531,
      parentId: 3530,
      menuName: "RD 交接新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:handoff-order:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3532,
      parentId: 3530,
      menuName: "RD 交接作废",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:handoff-order:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3540,
      parentId: 3500,
      menuName: "RD 盘点单",
      orderNum: 4,
      path: "stocktake-orders",
      component: "rd/stocktake-orders/index",
      routeName: "RdStocktakeOrders",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "rd:stocktake-order:list",
      icon: "list",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3541,
      parentId: 3540,
      menuName: "RD 盘点单新增",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:stocktake-order:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3542,
      parentId: 3540,
      menuName: "RD 盘点单作废",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:stocktake-order:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3600,
      parentId: 0,
      menuName: "研发项目权限",
      orderNum: 16,
      path: "/rd-project-auth",
      component: "Layout",
      routeName: "RdProjectPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "tree-table",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3610,
      parentId: 3600,
      menuName: "研发项目台账",
      orderNum: 1,
      path: "projects",
      component: "rd/projects/index",
      routeName: "RdProjectLedger",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "rd:project:list",
      icon: "tree-table",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3611,
      parentId: 3610,
      menuName: "研发项目详情",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:project:get",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3612,
      parentId: 3610,
      menuName: "研发项目新增",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:project:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3613,
      parentId: 3610,
      menuName: "研发项目修改",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:project:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3614,
      parentId: 3610,
      menuName: "研发项目作废",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "rd:project:void",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3700,
      parentId: 0,
      menuName: "审核权限",
      orderNum: 17,
      path: "/approval-document-auth",
      component: "Layout",
      routeName: "ApprovalDocumentPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "edit",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3710,
      parentId: 3700,
      menuName: "审核状态",
      orderNum: 1,
      path: "document-status",
      component: "",
      routeName: "",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "approval:document:status",
      icon: "edit",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3711,
      parentId: 3700,
      menuName: "审核列表",
      orderNum: 2,
      path: "documents",
      component: "",
      routeName: "",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "approval:document:list",
      icon: "edit",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3712,
      parentId: 3711,
      menuName: "发起审核",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "approval:document:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3713,
      parentId: 3711,
      menuName: "审核通过",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "approval:document:approve",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3714,
      parentId: 3711,
      menuName: "审核驳回",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "approval:document:reject",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3715,
      parentId: 3711,
      menuName: "审核重置",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "approval:document:reset",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3900,
      parentId: 0,
      menuName: "调度中心权限",
      orderNum: 18,
      path: "/scheduler-auth",
      component: "Layout",
      routeName: "SchedulerPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "clock",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3910,
      parentId: 3900,
      menuName: "调度任务",
      orderNum: 1,
      path: "jobs",
      component: "scheduler/jobs/index",
      routeName: "SchedulerJobs",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "scheduler:job:list",
      icon: "clock",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3911,
      parentId: 3910,
      menuName: "新增任务",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "scheduler:job:create",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3912,
      parentId: 3910,
      menuName: "修改任务",
      orderNum: 2,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "scheduler:job:update",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3913,
      parentId: 3910,
      menuName: "立即执行",
      orderNum: 3,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "scheduler:job:run",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3914,
      parentId: 3910,
      menuName: "暂停恢复",
      orderNum: 4,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "scheduler:job:pause",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3915,
      parentId: 3900,
      menuName: "调度日志",
      orderNum: 2,
      path: "job-logs",
      component: "scheduler/job-logs/index",
      routeName: "SchedulerLogs",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "scheduler:job:log:list",
      icon: "clock",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3950,
      parentId: 0,
      menuName: "AI 助手权限",
      orderNum: 19,
      path: "/ai-auth",
      component: "Layout",
      routeName: "AiPermissions",
      menuType: "M",
      visible: "0",
      status: "0",
      perms: "",
      icon: "message",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3951,
      parentId: 3950,
      menuName: "AI 对话",
      orderNum: 1,
      path: "chat",
      component: "ai/assistant/index",
      routeName: "AiAssistant",
      menuType: "C",
      visible: "0",
      status: "0",
      perms: "ai:chat",
      icon: "message",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
    {
      menuId: 3952,
      parentId: 3951,
      menuName: "AI 工具列表",
      orderNum: 1,
      path: "",
      component: "",
      routeName: "",
      menuType: "F",
      visible: "0",
      status: "0",
      perms: "ai:tools:list",
      icon: "",
      query: "",
      isFrame: "1",
      isCache: "0",
    },
  ];

  const roles: ManagedRoleRecord[] = [
    {
      roleId: 1,
      roleName: "系统管理员",
      roleKey: "admin",
      roleSort: 1,
      status: "0",
      dataScope: "1",
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      menuIds: [],
      deptIds: [100, 200, 300],
      remark: "超级管理员角色",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      roleId: 2,
      roleName: "仓库管理员",
      roleKey: "warehouse-manager",
      roleSort: 2,
      status: "0",
      dataScope: "3",
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      menuIds: [],
      deptIds: [300],
      remark: "主仓与公司级实物流转角色",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      roleId: 3,
      roleName: "研发小仓管理员",
      roleKey: "rd-operator",
      roleSort: 3,
      status: "0",
      dataScope: "3",
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      menuIds: [],
      deptIds: [100],
      remark: "研发小仓专属角色",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      roleId: 4,
      roleName: "采购人员",
      roleKey: "procurement",
      roleSort: 4,
      status: "0",
      dataScope: "3",
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      menuIds: [],
      deptIds: [200],
      remark: "采购执行与验收回看角色",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
  ];

  const dictTypes: ManagedDictTypeRecord[] = [
    {
      dictId: 1,
      dictName: "通用状态",
      dictType: "sys_normal_disable",
      status: "0",
      remark: "启用停用状态",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictId: 2,
      dictName: "用户性别",
      dictType: "sys_user_sex",
      status: "0",
      remark: "用户性别字典",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictId: 3,
      dictName: "系统内置",
      dictType: "sys_yes_no",
      status: "0",
      remark: "系统内置字典",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictId: 4,
      dictName: "公告类型",
      dictType: "sys_notice_type",
      status: "0",
      remark: "通知公告类型",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictId: 5,
      dictName: "公告状态",
      dictType: "sys_notice_status",
      status: "0",
      remark: "通知公告状态",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
  ];

  const dictData: ManagedDictDataRecord[] = [
    {
      dictCode: 1,
      dictSort: 1,
      dictLabel: "正常",
      dictValue: "0",
      dictType: "sys_normal_disable",
      cssClass: "",
      listClass: "success",
      isDefault: "Y",
      status: "0",
      remark: "默认启用",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 2,
      dictSort: 2,
      dictLabel: "停用",
      dictValue: "1",
      dictType: "sys_normal_disable",
      cssClass: "",
      listClass: "danger",
      isDefault: "N",
      status: "0",
      remark: "停用状态",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 3,
      dictSort: 1,
      dictLabel: "男",
      dictValue: "0",
      dictType: "sys_user_sex",
      cssClass: "",
      listClass: "",
      isDefault: "Y",
      status: "0",
      remark: "",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 4,
      dictSort: 2,
      dictLabel: "女",
      dictValue: "1",
      dictType: "sys_user_sex",
      cssClass: "",
      listClass: "",
      isDefault: "N",
      status: "0",
      remark: "",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 5,
      dictSort: 3,
      dictLabel: "未知",
      dictValue: "2",
      dictType: "sys_user_sex",
      cssClass: "",
      listClass: "info",
      isDefault: "N",
      status: "0",
      remark: "",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 6,
      dictSort: 1,
      dictLabel: "是",
      dictValue: "Y",
      dictType: "sys_yes_no",
      cssClass: "",
      listClass: "success",
      isDefault: "Y",
      status: "0",
      remark: "",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 7,
      dictSort: 2,
      dictLabel: "否",
      dictValue: "N",
      dictType: "sys_yes_no",
      cssClass: "",
      listClass: "warning",
      isDefault: "N",
      status: "0",
      remark: "",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 8,
      dictSort: 1,
      dictLabel: "通知",
      dictValue: "1",
      dictType: "sys_notice_type",
      cssClass: "",
      listClass: "primary",
      isDefault: "Y",
      status: "0",
      remark: "",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 9,
      dictSort: 2,
      dictLabel: "公告",
      dictValue: "2",
      dictType: "sys_notice_type",
      cssClass: "",
      listClass: "warning",
      isDefault: "N",
      status: "0",
      remark: "",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 10,
      dictSort: 1,
      dictLabel: "正常",
      dictValue: "0",
      dictType: "sys_notice_status",
      cssClass: "",
      listClass: "success",
      isDefault: "Y",
      status: "0",
      remark: "",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      dictCode: 11,
      dictSort: 2,
      dictLabel: "关闭",
      dictValue: "1",
      dictType: "sys_notice_status",
      cssClass: "",
      listClass: "info",
      isDefault: "N",
      status: "0",
      remark: "",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
  ];

  const configs: ManagedConfigRecord[] = [
    {
      configId: 1,
      configName: "用户默认密码",
      configKey: "sys.user.initPassword",
      configValue: "ChangeMe123",
      configType: "Y",
      remark: "用户新增时的初始密码",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
    {
      configId: 2,
      configName: "系统标题",
      configKey: "sys.app.title",
      configValue: "Saifute WMS",
      configType: "N",
      remark: "前端展示标题",
      createdAt: "2026-03-01T09:00:00.000Z",
    },
  ];

  const notices: ManagedNoticeRecord[] = [
    {
      noticeId: 1,
      noticeTitle: "RBAC 骨架已切换到新系统真源",
      noticeType: "1",
      noticeContent:
        "<p>系统管理菜单、接口和权限链路已由当前 NestJS + web 仓库承接。</p>",
      status: "0",
      remark: "Phase 2 骨架公告",
      createdAt: "2026-03-27T09:00:00.000Z",
    },
    {
      noticeId: 2,
      noticeTitle: "研发小仓账号保持独立控制台",
      noticeType: "2",
      noticeContent:
        "<p><strong>rd-operator</strong> 仍只进入研发小仓控制台，admin 不再被额外裁掉相关页面。</p>",
      status: "0",
      remark: "Phase 1 验证公告",
      createdAt: "2026-03-27T09:30:00.000Z",
    },
  ];

  const users: ManagedUserRecord[] = [
    {
      userId: 1,
      deptId: 300,
      userName: "admin",
      nickName: "系统管理员",
      avatarUrl: null,
      email: "admin@saifute.local",
      phonenumber: "13800000001",
      sex: "0",
      status: "0",
      deleted: false,
      remark: "超级管理员账号",
      createdAt: "2026-03-01T09:00:00.000Z",
      postIds: [1],
      roleIds: [1],
      passwordHash: hashText("admin123"),
      consoleMode: "default",
      stockScope: {
        mode: "ALL",
        stockScope: null,
        stockScopeName: null,
      },
      workshopScope: {
        mode: "ALL",
        workshopId: null,
        workshopName: null,
      },
      extraPermissions: [
        ALL_PERMISSION,
        "dashboard:view",
        "monitor:online:list",
        "monitor:online:forceLogout",
        "audit:login-log:list",
        "audit:login-log:delete",
        "audit:oper-log:list",
        "audit:oper-log:delete",
        "approval:document:status",
        "approval:document:list",
        "approval:document:create",
        "approval:document:approve",
        "approval:document:reject",
        "approval:document:reset",
        "reporting:home:view",
        "reporting:inventory-summary:view",
        "reporting:material-category-summary:view",
        "reporting:monthly-reporting:view",
        "reporting:trends:view",
        "reporting:export",
        "scheduler:job:list",
        "scheduler:job:create",
        "scheduler:job:update",
        "scheduler:job:run",
        "scheduler:job:pause",
        "scheduler:job:log:list",
        "ai:chat",
        "ai:tools:list",
        "master:material-category:list",
        "master:material-category:create",
        "master:material-category:update",
        "master:material-category:deactivate",
        "master:material:list",
        "master:material:create",
        "master:material:update",
        "master:material:deactivate",
        "master:customer:list",
        "master:customer:create",
        "master:customer:update",
        "master:customer:deactivate",
        "master:supplier:list",
        "master:supplier:create",
        "master:supplier:update",
        "master:supplier:deactivate",
        "master:personnel:list",
        "master:personnel:create",
        "master:personnel:update",
        "master:personnel:deactivate",
        "master:workshop:list",
        "master:workshop:create",
        "master:workshop:update",
        "master:workshop:deactivate",
        "master:stock-scope:list",
        "master:stock-scope:create",
        "master:stock-scope:update",
        "master:stock-scope:deactivate",
        "inbound:order:list",
        "inbound:order:create",
        "inbound:order:update",
        "inbound:order:void",
        "inbound:into-order:list",
        "inbound:into-order:create",
        "inbound:into-order:update",
        "inbound:into-order:void",
        "rd:procurement-request:list",
        "rd:procurement-request:create",
        "rd:procurement-request:void",
        "rd:procurement-request:status-action",
        "rd:handoff-order:list",
        "rd:handoff-order:create",
        "rd:handoff-order:void",
        "rd:stocktake-order:list",
        "rd:stocktake-order:create",
        "rd:stocktake-order:void",
        "workshop-material:pick-order:list",
        "workshop-material:pick-order:create",
        "workshop-material:pick-order:update",
        "workshop-material:pick-order:void",
        "workshop-material:return-order:list",
        "workshop-material:return-order:create",
        "workshop-material:return-order:update",
        "workshop-material:return-order:void",
        "workshop-material:scrap-order:list",
        "workshop-material:scrap-order:create",
        "workshop-material:scrap-order:update",
        "workshop-material:scrap-order:void",
        "rd:project:list",
        "rd:project:get",
        "rd:project:create",
        "rd:project:update",
        "rd:project:void",
        "inventory:balance:list",
        "inventory:factory-number:list",
        "inventory:log:list",
        "inventory:source-usage:list",
        "sales:order:list",
        "sales:order:create",
        "sales:order:update",
        "sales:order:void",
        "sales:return:list",
        "sales:return:create",
        "sales:return:void",
        "sales:project:list",
        "sales:project:get",
        "sales:project:create",
        "sales:project:update",
        "sales:project:void",
        "sales:project:draft",
        "rd:workbench:view",
      ],
    },
    {
      userId: 2,
      deptId: 300,
      userName: "operator",
      nickName: "仓库管理员",
      avatarUrl: null,
      email: "warehouse-manager@saifute.local",
      phonenumber: "13800000006",
      sex: "0",
      status: "0",
      deleted: false,
      remark: "主仓与公司级实物流转代表账号",
      createdAt: "2026-03-01T09:10:00.000Z",
      postIds: [2],
      roleIds: [2],
      passwordHash: hashText("operator123"),
      consoleMode: "default",
      stockScope: {
        mode: "ALL",
        stockScope: null,
        stockScopeName: null,
      },
      workshopScope: {
        mode: "ALL",
        workshopId: null,
        workshopName: null,
      },
      extraPermissions: [],
    },
    {
      userId: 3,
      deptId: 300,
      userName: "disabled-user",
      nickName: "停用仓库账号",
      avatarUrl: null,
      email: "disabled@saifute.local",
      phonenumber: "13800000007",
      sex: "0",
      status: "1",
      deleted: false,
      remark: "用于停用态校验",
      createdAt: "2026-03-01T09:20:00.000Z",
      postIds: [2],
      roleIds: [2],
      passwordHash: hashText("disabled123"),
      consoleMode: "default",
      stockScope: {
        mode: "ALL",
        stockScope: null,
        stockScopeName: null,
      },
      workshopScope: {
        mode: "ALL",
        workshopId: null,
        workshopName: null,
      },
      extraPermissions: [],
    },
    {
      userId: 4,
      deptId: 200,
      userName: "procurement",
      nickName: "采购人员",
      avatarUrl: null,
      email: "procurement-user@saifute.local",
      phonenumber: "13800000008",
      sex: "1",
      status: "0",
      deleted: false,
      remark: "采购执行代表账号",
      createdAt: "2026-03-01T09:30:00.000Z",
      postIds: [3],
      roleIds: [4],
      passwordHash: hashText("procurement123"),
      consoleMode: "default",
      stockScope: {
        mode: "ALL",
        stockScope: null,
        stockScopeName: null,
      },
      workshopScope: {
        mode: "ALL",
        workshopId: null,
        workshopName: null,
      },
      extraPermissions: [],
    },
    {
      userId: 5,
      deptId: 100,
      userName: "rd-operator",
      nickName: "研发小仓管理员",
      avatarUrl: null,
      email: "rd@saifute.local",
      phonenumber: "13800000009",
      sex: "0",
      status: "0",
      deleted: false,
      remark: "研发小仓专属账号",
      createdAt: "2026-03-01T09:40:00.000Z",
      postIds: [4],
      roleIds: [3],
      passwordHash: hashText("rd123456"),
      consoleMode: "rd-subwarehouse",
      stockScope: {
        mode: "FIXED",
        stockScope: "RD_SUB",
        stockScopeName: "研发小仓",
      },
      workshopScope: {
        mode: "ALL",
        workshopId: null,
        workshopName: null,
      },
      extraPermissions: [],
    },
  ];

  return buildSystemManagementSeedState({
    depts,
    posts,
    menus,
    roles,
    dictTypes,
    dictData,
    configs,
    notices,
    users,
  });
}

function buildSystemManagementSeedState(
  state: SystemManagementState,
): SystemManagementState {
  const permissionToMenuIds = new Map<string, number[]>();
  state.menus.forEach((menu) => {
    if (!menu.perms) {
      return;
    }
    const menuIds = permissionToMenuIds.get(menu.perms) ?? [];
    menuIds.push(menu.menuId);
    permissionToMenuIds.set(menu.perms, menuIds);
  });

  return {
    ...state,
    roles: state.roles.map((role) => {
      if (role.roleKey === "admin") {
        return {
          ...role,
          menuIds: state.menus.map((menu) => menu.menuId),
        };
      }

      const permissionKeys = DEFAULT_ROLE_PERMISSION_ASSIGNMENTS[role.roleKey];
      if (!permissionKeys) {
        return role;
      }

      return {
        ...role,
        menuIds: [
          ...new Set(
            permissionKeys.flatMap(
              (permissionKey) => permissionToMenuIds.get(permissionKey) ?? [],
            ),
          ),
        ],
      };
    }),
  };
}
